export const enum ERRORS_TYPES {
    BAD_REQUEST = "BAD REQUEST",
    UNAUTHORIZED = "UNATHORIZED",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT FOUND",
    INTERNAL_ERROR = "INTERNAL SERVER ERROR",
    IN_USE = "IN USE"
}

